// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS4VT8bSrs6yG0CzyBJdXsI80mJBoJS4I',
    appId: '1:1068167125190:web:f0bdeaaf31af10e2335fc7',
    messagingSenderId: '1068167125190',
    projectId: 'mimo-dd9dd',
    authDomain: 'mimo-dd9dd.firebaseapp.com',
    storageBucket: 'mimo-dd9dd.firebasestorage.app',
    measurementId: 'G-L27WDRYQT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiPAHbtKLOs6EjkD-xEH90FLTctAg5JLM',
    appId: '1:1068167125190:android:224460c04bb3b141335fc7',
    messagingSenderId: '1068167125190',
    projectId: 'mimo-dd9dd',
    storageBucket: 'mimo-dd9dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPjzguctXKjGMqH20LcI7iNfC-kjo6FDM',
    appId: '1:1068167125190:ios:8c1d00d29165c7aa335fc7',
    messagingSenderId: '1068167125190',
    projectId: 'mimo-dd9dd',
    storageBucket: 'mimo-dd9dd.firebasestorage.app',
    iosBundleId: 'com.example.mimo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPjzguctXKjGMqH20LcI7iNfC-kjo6FDM',
    appId: '1:1068167125190:ios:8c1d00d29165c7aa335fc7',
    messagingSenderId: '1068167125190',
    projectId: 'mimo-dd9dd',
    storageBucket: 'mimo-dd9dd.firebasestorage.app',
    iosBundleId: 'com.example.mimo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAS4VT8bSrs6yG0CzyBJdXsI80mJBoJS4I',
    appId: '1:1068167125190:web:c72e07c9a154dff8335fc7',
    messagingSenderId: '1068167125190',
    projectId: 'mimo-dd9dd',
    authDomain: 'mimo-dd9dd.firebaseapp.com',
    storageBucket: 'mimo-dd9dd.firebasestorage.app',
    measurementId: 'G-82PLDK83XS',
  );
}
